"""
Generated by typeshare 1.9.2
"""

from __future__ import annotations

from pydantic import BaseModel
from typing import List, Literal, Optional


class Item(BaseModel):
    """
    Represents a 1Password Item.
    """

    id: str
    """
    The item's unique ID
    """
    title: str
    """
    The item's title
    """
    category: ItemCategory
    """
    The item's category
    """
    vault_id: str
    """
    The ID of the vault where the item is saved
    """
    fields: List[ItemField]
    """
    The item's fields
    """
    sections: List[ItemSection]
    """
    The item's sections
    """


ItemCategory = Literal[
    "Login",
    "SecureNote",
    "CreditCard",
    "CryptoWallet",
    "Identity",
    "Password",
    "Document",
    "ApiCredentials",
    "BankAccount",
    "Database",
    "DriverLicense",
    "Email",
    "MedicalRecord",
    "Membership",
    "OutdoorLicense",
    "Passport",
    "Rewards",
    "Router",
    "Server",
    "SshKey",
    "SocialSecurityNumber",
    "SoftwareLicense",
    "Person",
    "Unsupported",
]


class ItemField(BaseModel):
    """
    Stores a field's title and value.
    """

    id: str
    """
    The field's ID
    """
    title: str
    """
    The field's title
    """
    section_id: Optional[str]
    """
    The ID of the section containing the field. Designated fields such as usernames and passwords don't need to specify a section.
    """
    field_type: ItemFieldType
    """
    The type of value stored in the field
    """
    value: str
    """
    The string representation of the field's value
    """


ItemFieldType = Literal["Text", "Concealed", "Unsupported"]


class ItemSection(BaseModel):
    """
    A section groups together multiple fields in an item.
    """

    id: str
    """
    The section's ID
    """
    title: str
    """
    The section's name
    """
