name: Prep Release V1

on:
  issue_comment:
    types: [created]

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get comment content
        id: comment
        run: |
          # Capture the comment body in a structured JSON format
          COMMENT_BODY="${{ toJSON(github.event.comment.body) }}"

          # Debugging output
          echo "COMMENT_BODY=$COMMENT_BODY"

          # Save it as an output for use in the next step
          echo "COMMENT_BODY=$COMMENT_BODY" >> $GITHUB_ENV

      - name: Parse version, build number, and notes
        id: parse
        run: |
          echo "Parsing version, build_number, and notes from the comment..."

          COMMENT_BODY=$(cat comment.json)

          # Extract values using jq
          VERSION=$(echo "$COMMENT_BODY" | jq -r .version)
          BUILD_NUMBER=$(echo "$COMMENT_BODY" | jq -r .build_number)
          RELEASE_NOTES=$(echo "$COMMENT_BODY" | jq -r .release_notes)

          # Debugging parsed values
          echo "VERSION=$VERSION"
          echo "BUILD_NUMBER=$BUILD_NUMBER"
          echo "RELEASE_NOTES=$RELEASE_NOTES"

          # Set outputs for future steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> src/release/RELEASE-NOTES


      - name: Run your script with version, build number, and notes
        run: |
            make prep-release "$VERSION" "$BUILD_NUMBER" "$RELEASE_NOTES"
