name: Prep Release V1

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
      build_number:
        description: 'Build number '
        required: true
        type: string
      release_notes:
        description: 'Release notes for the version'
        required: true
        type: string

jobs:
  update-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/')  # Only run on branches that start with sdk-core/
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get the version, build number, and release notes from inputs
        id: get_inputs
        run: |
          # Get inputs passed to the workflow
          VERSION="${{ github.event.inputs.version }}"
          BUILD_NUMBER="${{ github.event.inputs.build_number }}"
          RELEASE_NOTES="${{ github.event.inputs.release_notes }}"

          # Debugging output for parsed values
          echo "VERSION=$VERSION"
          echo "BUILD_NUMBER=$BUILD_NUMBER"
          echo "RELEASE_NOTES=$RELEASE_NOTES"

          # Save the parsed values for future steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
      - name: Set up Git user
        run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git config --global tag.gpgsign false
              git config --global commit.gpgsign false

      - name: Run your script with version, build number, and release notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            make prep-release VERSION="$VERSION" BUILD_NUMBER="$BUILD_NUMBER" RELEASE_NOTES="$RELEASE_NOTES"
